ecomprj/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    #home
    path("", views.index, name='index'),
    path("products/", views.product_list, name='product_list'),
    path("product/<pid>/", views.product_Detail, name='product_detail'),

    #category
    path("category/", views.category_list, name='category_list'),
    path("category/<cid>/", views.category_product_list, name='category_product_list1'),
    #vendor
    path("vendor/", views.vendor_list, name = "vendor_list"),
    path("vendor/<vid>/", views.vendor_detail, name = "vendor_detail"),

    #tags
    path("products/tag/<slug:tag_slug>/", views.tag_list, name  = "tags"),

    #review
    path("add_review/<int:pid>/", views.add_review, name = "add_review"),

    path("search/", views.search_view, name="search"),

    path("filter_product/", views.filter_product, name="filter_product"),
    
    #add to cart url
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),

    #cart page 
    path("cart/", views.cart_view, name="cart"),

    path("delete-from-cart/", views.delete_from_cart, name="delete-from-cart"),

    path("update_from_cart/", views.update_from_cart, name="update_from_cart"),

    path("checkout/", views.checkout_view, name="checkout"),

    path("dashboard/",views.customer_dashboard, name="dashboard"),

    path("dashboard/order/<int:id>", views.order_detail, name="order_detail"),

    path("make_default_address/", views.make_default_address, name="make_default-address"),

    path("add_to_wishlist/", views.add_to_wishlist, name="add_to_wishlist"),

    path("wishlist_view/", views.wishlist_view, name="wishlist"),

    path("remove_wishlist/", views.remove_wishlist, name="remove_wishlist"),


]

ecomprj/ecomprj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    path("ckeditor", include("ckeditor_uploader.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecomprj/core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget = forms.Textarea(attrs = {'placeholder':"write review"}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

ecomprj/core/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from core.models import Product, Vendor, Category, ProductImages, ProductReview, CartOrderItems, CartOrder, Wishlist, Address
from userauths.models import Profile
from django.db.models import Count, Avg
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from django.core import serializers

from django.db.models.functions import ExtractMonth
import calendar


# Create your views here.
def index(request):
    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published",featured=True)
    new_products = Product.objects.filter(product_status="published",featured=True).order_by("-id")[:10]

    tags = Product.tags.all
    # ProductReviews = ProductReview.objects.filter(product=products[])
    print(products)
    context = {
        "products" : products,
        "new_products":new_products,
        "tags":tags,
        # "ProductReview":ProductReviews
    }
    return render(request, "core/index.html", context)

def product_list(request):
    products = Product.objects.filter(product_status="published")
    # ProductReviews = ProductReview.objects.filter(product=products[])
    print(products)
    context = {
        "products" : products,
        # "ProductReview":ProductReviews
    }
    return render(request, "core/product_list.html", context)

def category_list(request):

    # categories = Category.objects.all()
    categories = Category.objects.all().annotate(product_count = Count("category"))
    context = {
        "categories":categories
    }
    return render(request, "core/category_list.html", context)

def category_product_list(request, cid):
    categories = Category.objects.all()
    category = Category.objects.get(cid = cid)
    product = Product.objects.filter(product_status = "published", category = category)

    context = {
        'category': category,
        'products':product,
        "categories":categories
    }
    return render(request, "core/category_product_list.html", context)

def vendor_list(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors" : vendors,
    }

    return render(request, "core/vendor_list.html", context)

def vendor_detail(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    product = Product.objects.filter(vendor=vendor,product_status = "published" )

    context = {
        "vendor" : vendor,
        "product" : product,
    }

    return render(request, "core/vendor_detail.html", context)

def product_Detail(request,pid):
    product = Product.objects.get(pid= pid)
    #product = get_object_or_404(Product, pid = pid)
    p_image = product.p_images.all()
    vendor = product.vendor
    products = Product.objects.filter(category = product.category).exclude(pid=pid)
    #All reviews
    reviews = ProductReview.objects.filter(product = product)
    #average rating 
    avg_rating = ProductReview.objects.filter(product = product).aggregate(rating = Avg('rating'))

    review_form = ProductReviewForm()

    # if uset has alredy filled the form than review form page will not be visdible to them
    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user = request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    context = {
        "p" : product,
        "p_images":p_image,
        "vendor":vendor,
        "products":products,
        "reviews" : reviews,
        "avg_rating" : avg_rating,
        "review_form": review_form,
        "make_review": make_review,
    }

    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):  #slug = rohan rathod ! rohan-rathod  


    products = Product.objects.filter(product_status="published").order_by("-id") #or -date

    tag = None
    if tag_slug:   # parametr
        tag = get_object_or_404(Tag, slug = tag_slug) # slug = each tag we are passing
        products = products.filter(tags__in=[tag])  #filter the product who hav tag elemnt in its tags field

    context = {
        "products" : products,
        "tag": tag,
    }

    return render(request, "core/tag.html", context)

def add_review(request, pid):
    product = Product.objects.get(pk = pid)
    user = request.user

    review = ProductReview.objects.create(        #creating new review 
        user = user,
        product = product,
        review = request.POST['review'],         #form review
        rating = request.POST['rating']
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
        
    }

    avg_rating = ProductReview.objects.filter(product=product).aggregate(rating = Avg('rating'))

    return JsonResponse(       #we are doing this using javascript
        {
        'bool': True,        #hidding form
        'context':context,
        'avg_review':avg_rating,
        }
    )

    #grab ahatever send in the form

def search_view(request):
    query = request.GET.get("q")   #input name

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products":products,
        "query":query,
    }

    return render(request, "core/search.html", context)

def filter_product(request):
    categories = request.GET.getlist('category[]')  # -> data send through ajax when we click on any tag to url 
    vendors = request.GET.getlist('vendor[]')   # -> url directs here we extract the data (id) filter product show it through ajax

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()   #-> distict = filtered product

    products = products.filter(price__gte = min_price)
    products = products.filter(price__lte = max_price)

    if (len(categories) > 0 ):
        products = products.filter(category__id__in = categories).distinct()   #field lookup -> category__name__id__category__ (selecting multiple obtions)  __in -> cheking  if id exits in category
    if (len(vendors) > 0 ):
        products = products.filter(vendor__id__in = vendors).distinct()   #field lookup -> category__name__id__category__ (selecting multiple obtions)  __in -> cheking  if id exits in category

    # context = {
    #     "products" : products,
    # }

    data = render_to_string("core/async/prduct-list.html", {"products": products})
    return JsonResponse({"data": data})

def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            request.session['cart_data_obj'].update(cart_product)
    else:
        request.session['cart_data_obj'] = cart_product

    
    totalsum = sum(
    float(item['price']) * float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    total = sum(
     float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    request.session['cart_total_price'] = int(totalsum)
    request.session['cart_total_products'] = int(total)


    return JsonResponse({'data': request.session['cart_data_obj'],'totalsum':request.session['cart_total_price'], 'total': request.session['cart_total_products']})

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for key, value in request.session['cart_data_obj'].items():
            cart_total_amount += int(value['qty']) * float(value['price'])
        return render(request, "core/cart.html", {'data': request.session['cart_data_obj'],'totalsum':request.session['cart_total_price'], 'total': request.session['cart_total_products'],'cart_total_ammount':cart_total_amount})  
    else:
        messages.warning(request, "Your Cart is Empty")
        return redirect( "core:index")


def delete_from_cart(request):
    product_id = str(request.GET['id'])

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for key, value in request.session['cart_data_obj'].items():
            cart_total_amount += int(value['qty']) * float(value['price'])
    
    
    
    totalsum = sum(
    float(item['price']) * float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    total = sum(
     float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    request.session['cart_total_price'] = int(totalsum)
    request.session['cart_total_products'] = int(total)

    context = render_to_string("core/async/cart-list.html", {'data': request.session['cart_data_obj'],'totalsum':request.session['cart_total_price'], 'total': request.session['cart_total_products']})

ecomprj/templates/core/async/cart-list.html
  <body>
    
    <div class="container mt-5" id="cart-list">
        <div>
            <div class="blocks p-7 m-6 align-self-start">
                <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '|';">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="#" style="text-decoration: none;">Home</a></li>
                      <li class="breadcrumb-item active" aria-current="page">Pages</li>
                      <li class="breadcrumb-item active" aria-current="page">Cart</li>
                    </ol>
                  </nav>
            </div>
        </div>
      

      <div class="row d-flex">
        <div class="col-lg-8">
            <div class="d-flex justify-content-between">
                <div>
                  <h2>Your Cart</h2>
                  <p>There are {{ total }} products in your cart</p>
                </div>
                <div>
                    <button
                  class="btn btn-suc mt-3 mb-1 p-2"
                  style="
                    color: rgb(0, 0, 0, 0.3);
                    border: 1px solid rgb(0, 0, 0, 0.2);
                    
                  "
                >
                  <i class="fas fa-trash"></i> Clear Cart
                </button>
                </div>
                
              </div>
          <div
            class=""
            style="
              border: 1px solid rgb(54, 54, 54, 0.2);
              border-radius: 20px;
              box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            "
          >
            <table class="table cart-table ">
              <thead>
                <tr class="cart-header " style="height: 50px;border-radius: 20px;">
                  <th scope="col" style="padding-left:30px;width: 700px;">Product</th>
                  <th scope="col">Unit Price</th>
                  <th scope="col" >Quantity</th>
                  <th scope="col">Subtotal</th>
                  <th scope="col">Remove</th>
                </tr>
              </thead>
              <tbody>
                <!-- Example Row 1 -->
                 {% for product_id, item in data.items %}
                <tr class="product-row">
                  <td class="p-2 ps-3" >
                    <div class="d-flex align-items-center">
                      <img
                        src="{{ item.image }}"
                        class="me-3"
                        alt="Product Image"
                        style="height: 90px; width: 90px;"
                      />
                      <div>
                        <div><a href="{% url 'core:product_detail' item.pid %}" class="product_id" data-index="{{product_id}}" style="text-decoration: none;">{{ item.title }}</a></div>
                        <small class="text-muted"
                          >Rating:
                          <span class="text-warning">&#9733; 4.0</span></small
                        >
                      </div>
                    </div>
                  </td>
                  <td class="p-4" style="padding: 30px;">{{item.price|floatformat:2}}</td>
                  <td class="p-4" style="padding: 5px;width: 70px">
                    <input
                      type="number"
                      class="form-control product-qty-{{product_id}}"
                      value="{{ item.qty }}"
                      min="1"
                      style="width: 70px"
                    />
                  </td>
                  <td class="fw-bolder p-4" style="color: rgb(0, 128, 0); padding: 30px;">${% widthratio item.price 1 item.qty %}</td>
                  <td class="p-4" style="padding: 30px;">
                    <button class="btn btn-danger btn-sm delete_product" data_prodct="{{product_id}}">
                        <i class="fas fa-trash"></i>
                      </button>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <hr>
          <div class="d-flex justify-content-between mt-4 mb-4">
            <button class="btn btn-success ps-3 pe-3" variant="ghost">
              ← Continue Shopping
            </button>
            <button class="btn btn-success ps-3 pe-3 update_product" >
              ↻ Update Cart
            </button>
          </div>
        </div>

        <div class="col-md-4">
            <div class="mt-5">


            </div>
          <div
            class="card "
            style="
              border-radius: 20px;
              box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
              margin-top:95px;
            "
          >
            <div class="card-body " >
              <div class="row mb-3">
                <div class="col-6">Subtotal</div>
                <div class="col-6">${{ totalsum|floatformat:2 }}</div>
              </div>
              <div class="row mb-3">
                <div class="col-6">Shipping</div>
                <div class="col-6">Free</div>
              </div>
              
              <div class="row">
                <div class="col-6"><b>Total</b></div>
                <div class="col-6"><b>${{ totalsum|floatformat:2 }}</b></div>
              </div>
              {% if total %}
              <a 
            class="btn btn-dark btn-block vendor-card p-2 mt-3" 
            href="{% url 'core:checkout' %}" 
            style="background-color: black;color: white;width: 100%"
          >
          Continue to checkout
          </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

ecomprj/templates/core/async/prduct-list.html
{% for p in products%}
                <div class="col hover-up active">
                    <div class="product-item vendor-card">
                    <span class="badge bg-success position-absolute m-3">-{{p.get_percentage | floatformat:0}}%</span>
                    <a href="#" class="btn-wishlist"><svg width="24" height="24"><use xlink:href="#heart"></use></svg></a>
                    <figure >
                        <a href="" title="Product Title">
                        <img src="{{ p.image.url }}"  class="img-fluid tab-image" style="width: 250px; height: 250px; object-fit: cover;">
                        </a>
                    </figure>
                    
                    <div class="row g-0">
                        <div class="col-md-4">
                        <p class="m-0">{{p.category}}</p>
                        </div>
                        <div class="col-md-8 text-end">
                        <span class="rating text-end"><svg width="24" height="24" class="text-primary mb-2"><use xlink:href="#star-solid"></use></svg> </span></div>
                        <!-- <span class="rating text-end"> </span> -->
                        </div>
                    <h3>{{ p.title }}</h3>
                    <div>
                        <!-- <span class="qty">{% if p.in_stock %}In-Stock{% else %}<p>Out-of-Stocks</p>{% endif %}</span><span class="rating"><svg width="24" height="24" class="text-primary"><use xlink:href="#star-solid"></use></svg> </span> -->
                        <span class="font-small text-muted">By <a href="vendoe-detail.html">{{p.vendor.title}}</a></span>
                    </div>
                    <span class="price">${{p.price}}</span>
                    <div class="d-flex align-items-center justify-content-between">
                        <div class="input-group product-qty">
                            <span class="input-group-btn">
                                <button type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus">
                                <svg width="16" height="16"><use xlink:href="#minus"></use></svg>
                                </button>
                            </span>
                            <input type="text" id="quantity" name="quantity" class="form-control input-number" value="1">
                            <span class="input-group-btn">
                                <button type="button" class="quantity-right-plus btn btn-success btn-number" data-type="plus">
                                    <svg width="16" height="16"><use xlink:href="#plus"></use></svg>
                                </button>
                            </span>
                        </div>
                        <a href="#" class="nav-link">Add to Cart <iconify-icon icon="uil:shopping-cart"></a>
                    </div>
                    </div>
                </div>
                {% endfor %}

ecomprj/templates/core/async/wishlist_list.html
<body>
  <div class="container pt-4 mb-5 pb-5" id="wish_list">
    <h1 class="mt-5">Your Wishlist</h1>
    <p>
      There are
      <b style="color: rgb(4, 129, 58)">{{w.count}}</b> products in the list!
    </p>

    <div class="product-table px-4">
      <table
        class="table mb-0 align-middle table-hover"
        style="border-radius: 20px"
      >
        <thead class="table-header">
          <tr>
            <th scope="col " class="" style="width: 40px">
              <input
                type="checkbox"
                class="form-check-input"
                style="border: 1px solid rgb(0, 0, 0, 0.4)"
              />
            </th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Stock Status</th>
            <th scope="col">Action</th>
            <th scope="col">Remove</th>
          </tr>
        </thead>
        <tbody>
          {% for w in w %}
          <tr>
            <td>
              <input
                type="checkbox"
                class="form-check-input"
                style="border: 1px solid rgb(0, 0, 0, 0.4)"
              />
            </td>
            <td class="product-cell">
              <img
                src="{{w.product.image.url}}"
                class="product-img"
                alt="product"
              />
              <div>
                <div class="-name">
                  <a
                    class="product-name"
                    href="{% url 'core:product_detail' w.product.pid %}"
                    style="text-decoration: none"
                  >
                    {{w.product.title|truncatechars:30}}
                  </a>
                </div>
                <div class="rating">
                  ★★★★☆
                  <span class="rating-number">(4.0)</span>
                </div>
              </div>
            </td>
            <td>
              <span
                >$<span
                  class="price product-price-{{ w.product.id }}"
                  value="{{ w.product.price }}"
                  >{{w.product.price}}</span
                ></span
              >
            </td>
            <td>
              {% if w.product.in_stock == True %}
              <span class="stock-status in-stock">In Stock</span>
              {% else %}
              <span class="stock-status out-stock">Out Stock</span>
              {% endif %}
            </td>
            <td>
              {% if w.product.in_stock %}

              <div class="add-cart">
                <input
                  type="hidden"
                  value="1"
                  class="product-qty-{{ w.product.id }}"
                  name=""
                  id=""
                />

                <input
                  type="hidden"
                  value="{{w.product.id}}"
                  class="product-id-{{ w.product.id }}"
                  name=""
                  id=""
                />
                <input
                  type="hidden"
                  value="{{w.product.title}}"
                  class="product-title-{{ w.product.id }}"
                  name=""
                  id=""
                />
                <input
                  type="hidden"
                  value="{{w.product.image.url}}"
                  class="product-image-{{ w.product.id }}"
                  name=""
                  id=""
                />
                <input
                  type="hidden"
                  value="{{w.product.pid}}"
                  class="product-pid-{{ w.product.id }}"
                  name=""
                  id=""
                />

                <button
                  class="add-to-cart vendor-card m-0 nav-link p-2 px-3 add-to-cart-btn"
                  id="add-to-cart-btn"
                  data-index="{{ w.product.id }}"
                >
                  Add to cart
                </button>
              </div>

              {% else %}
              <button class="contact-us p-2">Contact Us</button>
              {% endif %}
            </td>

            <td>
              <button
                class="remove-btn delete_wishlist"
                data-wishlist-id="{{w.id}}"
              >
                <i class="fas fa-trash"></i>
              </button>
            </td>
          </tr>
          {% empty %}
          <tr>
            <p>Nothing in Wishlist yet....</p>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>