ecomprj/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    #home
    path("", views.index, name='index'),
    path("products/", views.product_list, name='product_list'),
    path("product/<pid>/", views.product_Detail, name='product_detail'),

    #category
    path("category/", views.category_list, name='category_list'),
    path("category/<cid>/", views.category_product_list, name='category_product_list1'),
    #vendor
    path("vendor/", views.vendor_list, name = "vendor_list"),
    path("vendor/<vid>/", views.vendor_detail, name = "vendor_detail"),

    #tags
    path("products/tag/<slug:tag_slug>/", views.tag_list, name  = "tags"),

    #review
    path("add_review/<int:pid>/", views.add_review, name = "add_review"),

    path("search/", views.search_view, name="search"),

    path("filter_product/", views.filter_product, name="filter_product"),
    
    #add to cart url
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),

    #cart page 
    path("cart/", views.cart_view, name="cart"),

    path("delete-from-cart/", views.delete_from_cart, name="delete-from-cart"),

    path("update_from_cart/", views.update_from_cart, name="update_from_cart"),

    path("checkout/", views.checkout_view, name="checkout"),

    path("dashboard/",views.customer_dashboard, name="dashboard"),

    path("dashboard/order/<int:id>", views.order_detail, name="order_detail"),

    path("make_default_address/", views.make_default_address, name="make_default-address"),

    path("add_to_wishlist/", views.add_to_wishlist, name="add_to_wishlist"),

    path("wishlist_view/", views.wishlist_view, name="wishlist"),

    path("remove_wishlist/", views.remove_wishlist, name="remove_wishlist"),


]

ecomprj/ecomprj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    path("ckeditor", include("ckeditor_uploader.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecomprj/userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("contectus/", views.contectus, name="contectus"),
    path("ajax_contectus/", views.ajx_contectus, name="ajx_contectus"),
    path("profile/edit/", views.profile_update, name="profile_update"),


]

ecomprj/core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget = forms.Textarea(attrs = {'placeholder':"write review"}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

ecomprj/core/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from core.models import Product, Vendor, Category, ProductImages, ProductReview, CartOrderItems, CartOrder, Wishlist, Address
from userauths.models import Profile
from django.db.models import Count, Avg
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from django.core import serializers

from django.db.models.functions import ExtractMonth
import calendar


# Create your views here.
def index(request):
    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published",featured=True)
    new_products = Product.objects.filter(product_status="published",featured=True).order_by("-id")[:10]

    tags = Product.tags.all
    # ProductReviews = ProductReview.objects.filter(product=products[])
    print(products)
    context = {
        "products" : products,
        "new_products":new_products,
        "tags":tags,
        # "ProductReview":ProductReviews
    }
    return render(request, "core/index.html", context)

def product_list(request):
    products = Product.objects.filter(product_status="published")
    # ProductReviews = ProductReview.objects.filter(product=products[])
    print(products)
    context = {
        "products" : products,
        # "ProductReview":ProductReviews
    }
    return render(request, "core/product_list.html", context)

def category_list(request):

    # categories = Category.objects.all()
    categories = Category.objects.all().annotate(product_count = Count("category"))
    context = {
        "categories":categories
    }
    return render(request, "core/category_list.html", context)

def category_product_list(request, cid):
    categories = Category.objects.all()
    category = Category.objects.get(cid = cid)
    product = Product.objects.filter(product_status = "published", category = category)

    context = {
        'category': category,
        'products':product,
        "categories":categories
    }
    return render(request, "core/category_product_list.html", context)

def vendor_list(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors" : vendors,
    }

    return render(request, "core/vendor_list.html", context)

def vendor_detail(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    product = Product.objects.filter(vendor=vendor,product_status = "published" )

    context = {
        "vendor" : vendor,
        "product" : product,
    }

    return render(request, "core/vendor_detail.html", context)

def product_Detail(request,pid):
    product = Product.objects.get(pid= pid)
    #product = get_object_or_404(Product, pid = pid)
    p_image = product.p_images.all()
    vendor = product.vendor
    products = Product.objects.filter(category = product.category).exclude(pid=pid)
    #All reviews
    reviews = ProductReview.objects.filter(product = product)
    #average rating 
    avg_rating = ProductReview.objects.filter(product = product).aggregate(rating = Avg('rating'))

    review_form = ProductReviewForm()

    # if uset has alredy filled the form than review form page will not be visdible to them
    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user = request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    context = {
        "p" : product,
        "p_images":p_image,
        "vendor":vendor,
        "products":products,
        "reviews" : reviews,
        "avg_rating" : avg_rating,
        "review_form": review_form,
        "make_review": make_review,
    }

    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):  #slug = rohan rathod ! rohan-rathod  


    products = Product.objects.filter(product_status="published").order_by("-id") #or -date

    tag = None
    if tag_slug:   # parametr
        tag = get_object_or_404(Tag, slug = tag_slug) # slug = each tag we are passing
        products = products.filter(tags__in=[tag])  #filter the product who hav tag elemnt in its tags field

    context = {
        "products" : products,
        "tag": tag,
    }

    return render(request, "core/tag.html", context)

def add_review(request, pid):
    product = Product.objects.get(pk = pid)
    user = request.user

    review = ProductReview.objects.create(        #creating new review 
        user = user,
        product = product,
        review = request.POST['review'],         #form review
        rating = request.POST['rating']
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
        
    }

    avg_rating = ProductReview.objects.filter(product=product).aggregate(rating = Avg('rating'))

    return JsonResponse(       #we are doing this using javascript
        {
        'bool': True,        #hidding form
        'context':context,
        'avg_review':avg_rating,
        }
    )

    #grab ahatever send in the form

def search_view(request):
    query = request.GET.get("q")   #input name

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products":products,
        "query":query,
    }

    return render(request, "core/search.html", context)

def filter_product(request):
    categories = request.GET.getlist('category[]')  # -> data send through ajax when we click on any tag to url 
    vendors = request.GET.getlist('vendor[]')   # -> url directs here we extract the data (id) filter product show it through ajax

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()   #-> distict = filtered product

    products = products.filter(price__gte = min_price)
    products = products.filter(price__lte = max_price)

    if (len(categories) > 0 ):
        products = products.filter(category__id__in = categories).distinct()   #field lookup -> category__name__id__category__ (selecting multiple obtions)  __in -> cheking  if id exits in category
    if (len(vendors) > 0 ):
        products = products.filter(vendor__id__in = vendors).distinct()   #field lookup -> category__name__id__category__ (selecting multiple obtions)  __in -> cheking  if id exits in category

    # context = {
    #     "products" : products,
    # }

    data = render_to_string("core/async/prduct-list.html", {"products": products})
    return JsonResponse({"data": data})

def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            request.session['cart_data_obj'].update(cart_product)
    else:
        request.session['cart_data_obj'] = cart_product

    
    totalsum = sum(
    float(item['price']) * float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    total = sum(
     float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    request.session['cart_total_price'] = int(totalsum)
    request.session['cart_total_products'] = int(total)


    return JsonResponse({'data': request.session['cart_data_obj'],'totalsum':request.session['cart_total_price'], 'total': request.session['cart_total_products']})

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for key, value in request.session['cart_data_obj'].items():
            cart_total_amount += int(value['qty']) * float(value['price'])
        return render(request, "core/cart.html", {'data': request.session['cart_data_obj'],'totalsum':request.session['cart_total_price'], 'total': request.session['cart_total_products'],'cart_total_ammount':cart_total_amount})  
    else:
        messages.warning(request, "Your Cart is Empty")
        return redirect( "core:index")


def delete_from_cart(request):
    product_id = str(request.GET['id'])

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for key, value in request.session['cart_data_obj'].items():
            cart_total_amount += int(value['qty']) * float(value['price'])
    
    
    
    totalsum = sum(
    float(item['price']) * float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    total = sum(
     float(item['qty']) 
    for item in request.session['cart_data_obj'].values()
    )
    request.session['cart_total_price'] = int(totalsum)
    request.session['cart_total_products'] = int(total)

    context = render_to_string("core/async/cart-list.html", {'data': request.session['cart_data_obj'],'totalsum':request.session['cart_total_price'], 'total': request.session['cart_total_products']})

ecomprj/templates/core/checkout.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}

<body>
  <div class="container my-5">
    <div class="row">
      <h1 style="color: black; font-weight: 600">Checkout</h1>
      <h6 style="color: black">
        There are <span>{{total}}</span> prducts in your cart
      </h6>
      <!-- Billing Details -->
      <div class="col-md-7">
        <div class="row mb-3">
          <div
            class="col-md-6 mt-4 mb-4"
            style="border: 1px solid rgb(0, 0, 0, 0.2); border-radius: 20px"
          >
            <a
              href="#"
              class="login-link mb-4 small"
              style="text-decoration: none"
            >
              <i class="fas fa-user me-2"></i>
              <span style="color: #666">Already have an account?</span>
              Click here to login
            </a>
          </div>
        </div>

        <h3 class="" style="color: black">Billing Details</h3>
        <form>
          <div class="row mb-3">
            <div class="col-md-6">
              <input
                type="text"
                class="form-control"
                value="{{request.user|title}}"
                placeholder="First Name *"
                style="color: black"
                required
              />
            </div>
            <div class="col-md-6">
              <input
                type="text"
                class="form-control"
                value="{{user_address.mobile}}"
                placeholder="Mobile *"
                style="color: black"
                required
              />
            </div>
          </div>
          <div class="mb-3">
            <input
              type="text"
              class="form-control"
              value="{{user_address.address}}"
              placeholder="Address *"
              style="color: black"
              required
            />
          </div>

          <div class="form-check mb-3">
            <input
              type="checkbox"
              class="form-check-input"
              id="create-account"
            />
            <label class="form-check-label" for="create-account"
              >Create an account</label
            >
          </div>
          <div class="form-check mb-3">
            <input
              type="checkbox"
              class="form-check-input"
              id="ship-different-address"
            />
            <label class="form-check-label" for="ship-different-address"
              >Ship to a different address</label
            >
          </div>
        </form>
      </div>

      <!-- Order Summary -->
      <div class="col-md-5">
        <div
          class="p-4"
          style="border: 1px solid rgb(0, 0, 0, 0.2); border-radius: 10px"
        >
          <div class="d-flex justify-content-between mt-3 me-3">
            <h4 style="color: black; font-weight: 600">Your Order</h4>
            <span class="text-muted"
              >Subtotal -
              <span class="text-brand" style="color: #2e8b57; font-weight: 600"
                >${{totalsum|floatformat:2}}</span
              ></span
            >
          </div>

          <hr />
          <a
            class="btn btn-success vendor-card p-2 mt-2 mb-2 ps-3 pe-3"
            href="{% url 'core:cart' %}"
            style="width: 40%; color: white"
          >
            <i class="fa-solid fa-cart-shopping"></i> Go Back to Cart
          </a>
          <hr />
          <!-- Product Items -->
          {% for p_id,item in data.items %}
          <div class="d-flex align-items-center" style="padding: 5px 0">
            <img src="{{ item.image }}" alt="Product" class="product-image" />
            <div class="product-details">
              <a
                href="{% url 'core:product_detail' item.pid %}"
                style="text-decoration: none"
              >
                <h6 style="color: black; font-weight: 600">{{item.title}}</h6>
              </a>
            </div>
            <span class="quantity small text-muted" style="margin-left: auto"
              >x{{item.qty}}</span
            >
            <span class="ps-4 text-muted">${{item.price}}</span>
            <span class="price me-3 bolder"
              >${% widthratio item.price 1 item.qty %}</span
            >
          </div>
          <hr />
          {% endfor %}

          <!-- Subtotal -->
        </div>

        <div class="row mt-4">
          <div class="col-md-12">
            <div class="payment-section">
              <h4 class="strong mb-4">Payment</h4>
              <div class="form-check mb-2">
                <input
                  type="radio"
                  class="form-check-input"
                  id="bank-transfer"
                  name="payment"
                  value="bank"
                  checked
                />
                <label class="form-check-label" for="bank-transfer"
                  >Direct Bank Transfer</label
                >
              </div>
              <div class="form-check mb-2">
                <input
                  type="radio"
                  class="form-check-input"
                  id="cod"
                  name="payment"
                  value="cod"
                />
                <label class="form-check-label" for="cod"
                  >Cash on Delivery</label
                >
              </div>
              <div class="form-check mb-2">
                <input
                  type="radio"
                  class="form-check-input"
                  id="online"
                  name="payment"
                  value="online"
                />
                <label class="form-check-label" for="online"
                  >Online Gateway</label
                >
              </div>
              <!-- Place Order Button -->
              <button
                class="btn btn-success mt-4 ps-4 pe-4"
                style="color: white"
              >
                <i class="fa-solid fa-wand-magic-sparkles"></i> Place Order
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Payment Section -->
  </div>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>

{% endblock content %}

ecomprj/templates/core/order_detail.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}

<body>
  <div class="container-fluid">
    <div class="row">
      <!-- Sidebar -->
      <div class="col-md-3 col-lg-3 sidebar">
        <ul class="nav nav-tabs flex-column" id="myTab" role="tablist">
          <a
            href="{% url 'core:dashboard' %}"
            class="custom-nav-link m-0"
            id="dashboard-tab"
            style="
              padding-top: 2px;
              padding-bottom: 2px;
              text-decoration: none;
              height: 62px;
            "
            ><div class="custom-nav-item pt-2 pb-2 ps-4">
              <i class="fa-solid fa-sliders"></i>
              <span class="strong"> Dashboard</span>
            </div>
          </a>

          <li class="nav-item me-2" role="presentation">
            <a
              href="#"
              class="nav-link ps-4 active"
              id="order-tab"
              data-bs-toggle="tab"
              data-bs-target="#order"
              type="button"
              role="tab"
            >
              <i class="fa-solid fa-bag-shopping"></i
              ><span class="strong"> Orders</span>
            </a>
          </li>

          <a
            href="{% url 'userauths:sign-out'%}"
            class="custom-nav-link m-0"
            id="dashboard-tab"
            style="
              padding-top: 2px;
              padding-bottom: 2px;
              text-decoration: none;
              height: 62px;
            "
            ><div class="custom-nav-item pt-2 pb-2 ps-4">
              <i class="fa-solid fa-right-from-bracket"></i> Logout
            </div>
          </a>
        </ul>
      </div>

      <!-- Content -->
      <div class="tab-content col-md-7 col-lg-7 m-2 pe-3" id="myTabContent">
        <div class="tab-pane fade" id="dashboard" role="tabpanel">
          <h2>Hello {{request.user|title}}!</h2>
          <br />
          <p>From your account dashboard you can easily check & view</p>
        </div>
        <div class="tab-pane fade show active" id="order" role="tabpanel">
          <table
            class="table table-bordered"
            style="border: 1px solid rgb(0, 0, 0, 0.3); color: rgb(0, 0, 0)"
          >
            <thead>
              <tr>
                <th style="width: 30px">Order INV</th>
                <th style="width: 30px; height: 30px">Image</th>
                <th>Title</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {% for p in order_item %}
              <tr>
                <td>INV-{{p.id}}</td>
                <td style="width: 60px; height: 60px">
                  <p>
                    <img
                      src="{{p.images}}"
                      alt=""
                      style="width: 70px; height: 70px; object-fit: contain"
                    />
                  </p>
                </td>
                <td>{{p.item}}</td>

                <td>${{p.price}}</td>
                <td>${{p.qty}}</td>
                <td>${{p.total}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="tab-pane fade" id="trackyourorder" role="tabpanel">
          <h3>Your Orders</h3>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Order</th>
                <th>Date</th>
                <th>Status</th>
                <th>Total</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for o in orders %}
              <tr>
                <td>#{{o.id}}</td>
                <td>{{o.order_date}}</td>
                <td>Processing</td>
                <td>$125.00 for 2 items</td>
                <td><a href="#" class="text-success">View</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="tab-pane fade" id="myaddress" role="tabpanel">
          <div class="row">
            <h4 class="mb-4">{{ reviews.count}} review for "{{ p.title}}"</h4>
          </div>
        </div>
        <div class="tab-pane fade" id="accountdetail" role="tabpanel">
          <div class="row">
            <h4 class="mb-4">{{ reviews.count}} review for "{{ p.title}}"</h4>
          </div>
        </div>
        <div class="tab-pane fade" id="logout" role="tabpanel">
          <div class="row">
            <h4 class="mb-4">{{ reviews.count}} review for "{{ p.title}}"</h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap JS -->
</body>
{% endblock %}

ecomprj/templates/core/vendor_list.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 mb-3">
      <h1 class="mb-4 text-center"><strong>Vendors List</strong></h1>
    </div>
    <div class="col-md-12">
      <div class="d-flex justify-content-center align-items-center mb-5">
        <div class="search-container">
          <input
            type="text"
            placeholder="Search vendors (by name or ID)..."
            aria-label="Search"
          />
          <button>
            <i class="bi bi-search"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="d-flex justify-content-center align-items-center mb-5">
        <p>We have <strong style="color: green;">{{vendors.count}}</strong> vendor{{vendors.count|pluralize}} now</p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="d-flex justify-content-center align-items-center mb-5">
        <div>
          <select class="form-select d-inline w-auto" aria-label="Show">
            <option selected>Show: 50</option>
            <option value="10">10</option>
            <option value="25">25</option>
            <option value="100">100</option>
          </select>
          <select class="form-select d-inline w-auto" aria-label="Sort by">
            <option selected>Sort by: Featured</option>
            <option value="name">Name</option>
            <option value="rating">Rating</option>
          </select>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="row g-4">
        <!-- Vendor 1 -->
        {% for v in vendors %}
        <div class="col-md-6 mt-2">
          <div class="vendor-card p-3 bg-white" style="max-width: 700px;">


            <div class="row">
              <div class="col-md-12 d-flex">
                <a style="display:contents;" href="{% url 'core:vendor_detail' v.vid %}">
                <div class="col-md-3 me-2 d-flex flex-column justify-content-end align-items-center" style="background:url({{ v.image.url }});background-size:cover; 
                background-repeat: no-repeat; 
                border-radius: 10px;background-position: center; height: 200px;">
                 <p>
                    <span class="badge bg-dark ">{{v.product.all.count}} Products</span>
                  </p>
                </div>
                </a>
                <div class="col-md-9 mt-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <p class="mb-1" style="line-height:0.3cm;">Since {{ v.date| date:"Y"}}</p>
                        <span class="badge badge-new">New</span>
                    </div>
                  <h5 class="mt-3" style="line-height:0.1cm;">{{v.title}}</h5></p>
                 

                  <p class="text-muted mt-2 mb-2">
                    {{v.address}}
                  </p>
                  
                  <div class="d-flex justify-content-between align-items-end">
                    <p>Call Us: (+91) - {{v.contact}}</p>
                    <div class="d-flex justify-content-end align-items-end me-3">
                        <a href="{% url 'core:vendor_detail' v.vid %}" class="btn btn-success vendor-btn mb-2"
                            >Visit Store →</a
                          >
                        </div>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- Vendor 2 -->
        <div class="col-md-6 mt-2">
          <div class="vendor-card p-4 bg-white">
            <span class="badge badge-featured">Featured</span>
            <h5 class="mt-3">Mrs. Smith's Pie</h5>
            <p class="mb-1">Since 2012</p>
            <p><span class="badge bg-success">233 products</span></p>
            <p class="text-muted">
              Address: 5171 W Campbell Ave, Kent, Utah 53127, United States
            </p>
            <p>Call Us: (+91) - 540-025-124553</p>
            <div class="d-flex justify-content-between">
              <a href="#" class="btn btn-success vendor-btn">Visit Store →</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap Icons -->

    />
    <!-- Bootstrap JS -->
  </div>
</div>

<!-- Bootstrap JS -->
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script> -->

{% endblock content %}