ecomprj/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    #home
    path("", views.index, name='index'),
    path("products/", views.product_list, name='product_list'),
    path("product/<pid>/", views.product_Detail, name='product_detail'),

    #category
    path("category/", views.category_list, name='category_list'),
    path("category/<cid>/", views.category_product_list, name='category_product_list1'),
    #vendor
    path("vendor/", views.vendor_list, name = "vendor_list"),
    path("vendor/<vid>/", views.vendor_detail, name = "vendor_detail"),

    #tags
    path("products/tag/<slug:tag_slug>/", views.tag_list, name  = "tags"),

    #review
    path("add_review/<int:pid>/", views.add_review, name = "add_review"),

    path("search/", views.search_view, name="search"),

    path("filter_product/", views.filter_product, name="filter_product"),
    
    #add to cart url
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),

    #cart page 
    path("cart/", views.cart_view, name="cart"),

    path("delete-from-cart/", views.delete_from_cart, name="delete-from-cart"),

    path("update_from_cart/", views.update_from_cart, name="update_from_cart"),

    path("checkout/", views.checkout_view, name="checkout"),

    path("dashboard/",views.customer_dashboard, name="dashboard"),

    path("dashboard/order/<int:id>", views.order_detail, name="order_detail"),

    path("make_default_address/", views.make_default_address, name="make_default-address"),

    path("add_to_wishlist/", views.add_to_wishlist, name="add_to_wishlist"),

    path("wishlist_view/", views.wishlist_view, name="wishlist"),

    path("remove_wishlist/", views.remove_wishlist, name="remove_wishlist"),


]

ecomprj/ecomprj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    path("ckeditor", include("ckeditor_uploader.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecomprj/userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("contectus/", views.contectus, name="contectus"),
    path("ajax_contectus/", views.ajx_contectus, name="ajx_contectus"),
    path("profile/edit/", views.profile_update, name="profile_update"),


]

ecomprj/userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    email = models.EmailField(unique=True, null=False)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length = 100)
    
    USERNAME_FIELD = "email"             # while filling login form set username will accept email 
    REQUIRED_FIELDS = ['username']       # required fiels with email and password and password 2

    def __str__(self):
        
        return self.username                # functio return name when we see user table in admin database it returns name and shows name 
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    
    image = models.ImageField(upload_to="image", null=True, blank=True)
    bio = models.TextField(max_length=200, null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    verified = models.BooleanField(default=False)

    def __str__(self):
        
            return self.user.username

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

class ContectUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.IntegerField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

    def __str__(self):
        return self.name

def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_profile, sender=User)  # when user is created then create profile
post_save.connect(save_profile, sender=User)  # when user is saved then save profile

ecomprj/userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile

INPUT_CLASSES='form-control pt-3 pb-3 ps-4 mb-2' 
INPUT_STYLE = 'color: black'
#form-control form-control-lg



class userRegisterForm(UserCreationForm):   # class extending usercreationform class
    username = forms.CharField(widget=forms.TextInput(attrs={'class':INPUT_CLASSES,'placeholder':"Username", 'style':INPUT_STYLE}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':"Email",'class':INPUT_CLASSES, 'style':INPUT_STYLE}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Password",'class':INPUT_CLASSES, 'style':INPUT_STYLE}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Confirm Password",'class':INPUT_CLASSES, 'style':INPUT_STYLE}))


    class Meta:                             # things we want to work with
        model = User  #model we are interacting with
        fields = ['username', 'email']
        # widgets={
        #     'username':forms.TextInput(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        #     'email':forms.EmailInput(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        #     'password1':forms.PasswordInput(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        #     'password2':forms.PasswordInput(attrs={
        #         'pl'
        #         'class':INPUT_CLASSES
        #     }),
        # }

class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class':INPUT_CLASSES,'placeholder':"Full Name", 'style':INPUT_STYLE}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class':INPUT_CLASSES,'placeholder':"Bio"}))
    phone = forms.IntegerField(widget=forms.NumberInput(attrs={'class':INPUT_CLASSES,'placeholder':"Phone", 'style':INPUT_STYLE}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':INPUT_CLASSES,'placeholder':"Image", 'style':INPUT_STYLE}))
    class Meta:
        model = Profile
        fields = ['full_name', 'bio', 'phone', 'image', ]
        # widgets={
        #     'full_name':forms.TextInput(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        #     'bio':forms.Textarea(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        #     'phone':forms.NumberInput(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        #     'image':forms.FileInput(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        #     'verified':forms.CheckboxInput(attrs={
        #         'class':INPUT_CLASSES
        #     }),
        # }

ecomprj/userauths/views.py
from django.shortcuts import redirect,render
from userauths.forms import userRegisterForm, ProfileForm
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from django.conf import settings
from userauths.models import User, ContectUs, Profile

from django.http import JsonResponse

# User = settings.AUTH_USER_MODEL    #userauths.user we declared in setting


# Create your views here.
def register_view(request):

    if request.method == "POST":
        form = userRegisterForm(request.POST or None)  # take all the data from post request and and put it into form
        if form.is_valid():                                #if data is valid then save the form
            new_user = form.save()                          ## you can see user in admin panel
            username = form.cleaned_data.get("username")
            messages.success(request, f"hey {username}, Your Acccount Created Succesfully")  # flash massages
            new_user = authenticate(username = form.cleaned_data['email'],
                                    password = form.cleaned_data['password1']
            )
            print("User Register succesfully")
            login(request, new_user)
            return redirect("core:index")          # index page
                    
    else:
        form = userRegisterForm()  
        print("User Cannot Be Registered")

    context = {             # creating this dict to use userregisterform in template 
        'form': form        # assinig variable to key in dict
    }
    return render(request, "userauths/sign-up.html", context)


def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request,f"Hey You are Alredy Loged in")
        return redirect("core:index")

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email = email)
            print(user.username)
            user = authenticate(request, email= email, password = password)

            if user is not None:
                login(request, user)
                messages.success(request, "You logged in")
                return redirect("core:index")
            elif user is not None and user.password != password:
                messages.warning(request, "User does not exist create an accont")
            else:
                messages.warning(request, "User does not exist create an accont")

            
        except:
            messages.warning(request,f"User with {email} does not exist")
        
        
    return render(request, "userauths/sign-in.html")

def logout_view(request):
    logout(request)
    messages.success(request, "You have Loged out")

    return redirect('userauths:sign-in')

def contectus(request):
    
    return render(request, "core/contect.html")

def ajx_contectus(request):
    name = request.GET["name"] 
    email = request.GET["email"]
    phone = request.GET["phone"]
    subject = request.GET["subject"]
    message = request.GET["message"]

    contact = ContectUs.objects.create(name = name, email = email, phone = phone, subject = subject, message = message)

    context = {
        "bool": True,
        "massage": "Your message has been sent",
    }

    messages.success(request, "Massage Submited.")

    return JsonResponse({'data': context})

def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profilr = form.save(commit=False)
            profilr.user = request.user
            profilr.save()
            messages.success(request, "Profile updated successfully")
            return redirect("core:dashboard")
    else:
        form = ProfileForm(instance=profile)
        

    context = {
        "form": form,
        "profile": profile,
        
    }

    return render(request, "userauths/dashboard.html", context)

ecomprj/templates/userauths/profile-edit.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}

<body>
  <div class="container-fluid">
    <div class="row">
      <!-- Sidebar -->
      <div class="col-md-3 col-lg-3 sidebar">
        <ul class="nav nav-tabs flex-column" id="myTab" role="tablist">
          <a
            href="{% url 'core:dashboard' %}"
            class="custom-nav-link m-0"
            id="dashboard-tab"
            style="
              padding-top: 2px;
              padding-bottom: 2px;
              text-decoration: none;
              height: 62px;
            "
            ><div class="custom-nav-item pt-2 pb-2 ps-4">
              <i class="fa-solid fa-sliders"></i>
              <span class="strong"> Dashboard</span>
            </div>
          </a>

          <li class="nav-item me-2" role="presentation">
            <a
              href="#"
              class="nav-link active ps-4"
              id="accountdetail-tab"
              data-bs-toggle="tab"
              data-bs-target="#accountdetail"
              type="button"
              role="tab"
            >
              <i class="fa-solid fa-user"></i> Profile
            </a>
          </li>

          <a
            href="{% url 'userauths:sign-out'%}"
            class="custom-nav-link m-0"
            id="dashboard-tab"
            style="
              padding-top: 2px;
              padding-bottom: 2px;
              text-decoration: none;
              height: 62px;
            "
            ><div class="custom-nav-item pt-2 pb-2 ps-4">
              <i class="fa-solid fa-right-from-bracket"></i> Logout
            </div>
          </a>
        </ul>
      </div>

      <!-- Content -->
      <div class="tab-content col-md-7 col-lg-7 m-2 pe-3" id="myTabContent">
        {% if form.errors %}
        <div class="alert-danger alert">
          <strong>{{ form.errors }}</strong>
        </div>
        {% endif %}
        <div
          class="tab-pane fade show active"
          id="accountdetail"
          role="tabpanel"
        >
          <h2>Edit Profile</h2>
          <hr />

          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row d-flex justify-content-between align-items-center">
              <div class="mb-3 col-md-2 pe-4 pb-4">
                {% if profile.image %}
                <span class=""
                  ><img
                    src="{{profile.image.url}}"
                    alt=""
                    style="
                      object-fit: cover;
                      width: 150px;
                      height: 150px;
                      border-radius: 50%;
                    "
                /></span>
                {% else %}
                <span class=""
                  ><img
                    src="https://static.vecteezy.com/system/resources/previews/008/442/086/non_2x/illustration-of-human-icon-user-symbol-icon-modern-design-on-blank-background-free-vector.jpg"
                    alt=""
                    style="
                      object-fit: cover;
                      width: 150px;
                      height: 150px;
                      border-radius: 50%;
                    "
                /></span>
                {% endif %}
              </div>

              <div class="col-md-9">
                <div class="mb-3">{{form.full_name}}</div>
                <div class="mb-3">{{form.image}}</div>
                <div class="mb-3">{{form.phone}}</div>
              </div>
              <div class="col-md-12">
                <div class="mb-3">{{form.bio}}</div>
              </div>
              <button
                type="submit"
                class="btn btn-success submit mt-3 pt-3 pb-3 ps-4 pe-4"
                style="font-weight: 600; color: white; width: 30%"
              >
                Save Changes
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap JS -->
</body>

<script>
  const ctx = document.getElementById("myChart");

  new Chart(ctx, {
    type: "bar",
    data: {
      labels: {{month|safe}},
      datasets: [
        {
          label: "# of Votes",
          backgroundColor: "#15d59c",
          borderColor: "#15d59c",
          data: {{ total_order|safe }},
          borderWidth: 1,
        },
      ],
    },
    options: {
      scales: {
        y: {
          beginAtZero: true,
        },
      },
    },
  });
</script>

{% endblock %}

ecomprj/templates/userauths/sign-in.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}
<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" /> -->

<!-- 
    


    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
      rel="stylesheet"
    />

 

    

    Bootstrap CSS


< Style -->
<!-- <link
  rel="stylesheet"
  href="{% static 'assets/login/css/bootstrap.min.css' %}"
/> -->
<!-- <link rel="stylesheet" href="{% static 'assets/login/css/loginstyle.css' %}" /> -->

<!-- <title>Login #7</title>

  -->
<!-- <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/login/css/owl.carousel.min.css' %}"
    />
  </head> -->
<!-- <body> -->
<main>
  <br />
  <br />
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img
            src="{% static 'assets/login/images/undraw_remotely_2j6y.svg' %}"
            alt="Image"
            class="img-fluid"
          />
        </div>
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-8">
              {% if form.errors or form.non_field_errors %}
              <div class="alert alert-danger">
                {% for field in form %} {{ field.errors }} {% endfor %}
                {{form.non_field_errors }}
              </div>
              {% endif %}
              <div class="mb-4">
                <h3 class="text-dark"><b>Login</b></h3>
                <p class="mb-30">
                  Don't have a account
                  <a href="{% url 'userauths:sign-up'%}">Create here</a>
                </p>
              </div>
              <form action="#" method="POST">
                {% csrf_token %}

                <div class="form-group first mb-4">
                  <input
                    required
                    type="text"
                    class="form-control"
                    name="email"
                    id="email"
                    placeholder="Username or Email"
                  />
                </div>
                <div class="form-group last mb-4">
                  <input
                    required
                    name="password"
                    type="password"
                    class="form-control"
                    id="password"
                    placeholder="Your password"
                  />
                </div>

                <div class="d-flex mb-5 align-items-center">
                  <div class="form-check">
                    <input
                      class="form-check-input mt-2"
                      type="checkbox"
                      value=""
                      id="flexCheckChecked"
                      checked
                    />
                    <label class="form-check-label" for="flexCheckChecked">
                      Remember me
                    </label>
                  </div>
                  <span class="ml-auto"
                    ><a href="#" class="forgot-pass">Forgot Password</a></span
                  >
                </div>
                <div class="d-grid gap-2 col-6 mx-auto">
                  <input
                    type="submit"
                    value="Login"
                    class="btn byn-fill-out btn-block btn-lg btn-primary hover-up"
                  />
                </div>

                <span class="d-block text-left my-4 text-muted"
                  >&mdash; or login with &mdash;</span
                >

                <div class="social-login">
                  <a href="#" class="facebook">
                    <span class="icon-facebook mr-3"></span>
                  </a>
                  <a href="#" class="twitter">
                    <span class="icon-twitter mr-3"></span>
                  </a>
                  <a href="#" class="google">
                    <span class="icon-google mr-3"></span>
                  </a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
<!-- <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"
  ></script>
  <script src="{% static 'assets/login/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'assets/login/js/popper.min.js' %}"></script>
  <script src="{% static 'assets/login/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/login/js/main.js' %}"></script> -->
<!-- </body> -->
<!-- </html> -->
<!-- </html> -->
{% endblock content %}
<!-- </html> -->

ecomprj/templates/userauths/sign-up.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}
<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" /> -->

<!-- 
    


    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
      rel="stylesheet"
    />

 

    

    Bootstrap CSS


< Style -->
<!-- <link
  rel="stylesheet"
  href="{% static 'assets/login/css/bootstrap.min.css' %}"
/> -->
<!-- <link rel="stylesheet" href="{% static 'assets/login/css/loginstyle.css' %}" /> -->

<!-- <title>Login #7</title>

  -->
<!-- <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/login/css/owl.carousel.min.css' %}"
    />
  </head> -->
<!-- <body> -->
<br />
<br />
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img
          src="{% static 'assets/login/images/undraw_remotely_2j6y.svg' %}"
          alt="Image"
          class="img-fluid"
        />
      </div>
      <div class="col-md-6 contents">
        <div class="row justify-content-center">
          <div class="col-md-8">
            {% if form.errors or form.non_field_errors %}
            <div class="alert alert-danger">
              {% for field in form %} {{ field.errors }} {% endfor %}
              {{form.non_field_errors }}
            </div>
            {% endif %}
            <div class="mb-4">
              <h3 class="text-dark"><b>Create an Account</b></h3>
              <p class="mb-4">
                Alredy Have Account
                <a href="{% url 'userauths:sign-in'%}">Login</a>
              </p>
            </div>
            <form action="#" method="post">
              {% csrf_token %}

              <div class="mb-3">{{form.username}}</div>
              <div class="mb-3">{{form.email}}</div>
              <div class="mb-3">{{form.password1}}</div>
              <div class="mb-3">{{form.password2}}</div>
              <!-- <div class="form-group first">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" />
                  </div>
                  <div class="form-group last mb-4">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" />
                  </div> -->

              <div class="form-check">
                <input
                  class="form-check-input mt-2"
                  type="checkbox"
                  value=""
                  id="flexCheckChecked"
                  checked
                />
                <label class="form-check-label" for="flexCheckChecked">
                  Remember me
                </label>
              </div>
              <span class="ml-auto"
                ><a href="#" class="forgot-pass">Forgot Password</a></span
              >

              <div class="d-grid gap-2 col-6 mx-auto">
                <input
                  type="submit"
                  value="Submit & Register"
                  class="btn byn-fill-out btn-block btn-lg btn-primary hover-up"
                />
              </div>

              <span class="d-block text-left my-4 text-muted"
                >&mdash; or login with &mdash;</span
              >

              <div class="social-login">
                <a href="#" class="facebook">
                  <span class="icon-facebook mr-3"></span>
                </a>
                <a href="#" class="twitter">
                  <span class="icon-twitter mr-3"></span>
                </a>
                <a href="#" class="google">
                  <span class="icon-google mr-3"></span>
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"
  ></script>
  <script src="{% static 'assets/login/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'assets/login/js/popper.min.js' %}"></script>
  <script src="{% static 'assets/login/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/login/js/main.js' %}"></script> -->
<!-- </body> -->
<!-- </html> -->
<!-- </html> -->
{% endblock content %}
<!-- </html> -->